# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171203_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, null=True, verbose_name='正文MarkDown'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
