# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20171206_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-add_time',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
