# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180113_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
    ]
