# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180115_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.Article', verbose_name='插图')),
            ],
            options={
                'verbose_name': '插图',
                'verbose_name_plural': '插图',
            },
        ),
    ]
