# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171201_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
