# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatars', verbose_name='头像'),
        ),
    ]
