# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171201_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, default='这个人很懒，什么都没有说', null=True, verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='保密', max_length=256, null=True, verbose_name='地址'),
        ),
    ]
