# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20171204_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followeds',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='accounts.UserProfile'),
        ),
    ]
