# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171204_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followeds',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(null=True, related_name='followeds', to='accounts.UserProfile', verbose_name='关注他的人'),
        ),
    ]
