"""'为文章加入了浏览量字段'

Revision ID: 1fc8716487ea
Revises: f2b63fb5cb7d
Create Date: 2017-09-02 10:10:12.054001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc8716487ea'
down_revision = 'f2b63fb5cb7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('page_view', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'page_view')
    # ### end Alembic commands ###
