"""文章模型增加了markdown的html字段

Revision ID: a30607f8162f
Revises: 1fc8716487ea
Create Date: 2017-09-04 12:30:45.276740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30607f8162f'
down_revision = '1fc8716487ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('content_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'content_html')
    # ### end Alembic commands ###
