"""'为用户表增加了几个信息字段'

Revision ID: bc427e779de9
Revises: ef2bb046270a
Create Date: 2017-08-31 20:10:44.715388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc427e779de9'
down_revision = 'ef2bb046270a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
