"""拓展User模型，使其支持登录

Revision ID: c987f676581d
Revises: 
Create Date: 2017-08-29 16:52:15.458971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c987f676581d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=False))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
